#Game State Types
GAME_STATE = "GAME_STATE"
STOPPED = "STOPPED"
STARTED = "STARTED"
PAUSED = "PAUSED"
GAMEOVER = "GAMEOVER"

#MESSAGE TYPES
INIT_REQ = "INIT_REQ"
DELTA_UPDATE = "DELTA_UPDATE"


#MESSAGE OBJECTS
PLAYER_ID = "PLAYERID"
GAME_ID = "GAMEID"
DELTA = "DELTA"
CODE = "CODE"
